#ifdef WINDOWS

#ifndef ENGINE_WINDOWS_SYSTEM_DISPLAY_MANAGER_HPP
#define ENGINE_WINDOWS_SYSTEM_DISPLAY_MANAGER_HPP

#endif /* ENGINE_WINDOWS_SYSTEM_DISPLAY_MANAGER_HPP */

#endif /* WINDOWS */

/* EOF */
